# Generated by Django 4.2 on 2023-04-05 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Azs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('dt', models.CharField(max_length=150)),
                ('dt_taneko', models.CharField(max_length=150)),
                ('dt_winter', models.CharField(max_length=150)),
                ('dt_arctic', models.CharField(max_length=150)),
            ],
        ),
    ]
